config/routes.rb
  match "meeting_rooms/:id/comment_destroy/:comment_id"=> "meeting_rooms#comment_destroy", :as => :destroy_meeting_room_comment, :via => :delete

  resources :states do
    get :autocomplete_state_name, :on => :collection
  end
  get "admins/index"

  get "pages/index"

  match "pages/city/:city"=> "pages#city", :as => :state_city, :via => :get
  match "pages/school/:school"=> "pages#school", :as => :school_city, :via => :get
  match "pages/search_state/"=> "pages#search_state", :as => :search_state, :via => :get
  match "pages/country/"=> "pages#country", :as => :country, :via => :get
  match "pages/city_list/:country_id"=> "pages#city_list", :as => :city_list, :via => :get
  match "pages/states_list/"=> "pages#state_list", :as => :state_list, :via => :get

  namespace :admin do

    resources :admins do
      member do
        put "update"
        get "edit_school"
        put "update_school"
      end
      collection do
        get "school"
        get "new_school"
        post "create_school"
      end

    end

  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" } do
    get "welcome"=> "devise/registrations#index", :as => :welcome
  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
    match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
  end

  resources :activity_stream_preferences
  resources :activity_streams
  resources :class_rooms do

    match "reply/:comment_id"=> "comments#reply", :as => :reply_comment, :via => :post

    match "voteable_type/:id/comment_vote/:comment_id"=> "comments#index", :as => :comment_vote, :via => :get
    match "user_profiles/:student_id"=> "user_profiles#index", :as => :user_profile, :via => :get
    devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
      match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
    end

    resources :upload_files do

      member do
        get "comment_new"
        post "comment_create"
        
        get "student/:student_id", :action => "show", :as => :show_student_upload_file
        get "teacher/:teacher_id", :action => "show", :as => :show_teacher_upload_file
        get "comment_student/:student_id", :action => "comment_new", :as => :go_to_student_upload_file
        get "comment_teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_upload_file
      end
      
      collection do
        get "download"
        get "student/:student_id", :action => "index", :as => :student_upload_files_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_upload_files_index
      end
      
    end

    resources :notes do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_note
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_note
        get "download"
        put "remove_file"
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_notes_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_notes_index
      end
    end
    
    resources :to_dos do
      collection do
        get "selected_time"
      end
    end

    resources :messages do
      member do
        get "student/:student_id", :action => "inbox_detail", :as => :student_inbox_detail_observer
        get "teacher/:teacher_id", :action => "inbox_detail", :as => :teacher_inbox_detail_observer

        get "download"
        get "edit_draft"
        post 'delete_draft'
        delete 'student/:student_id', :action => :destroy, :as => :student_observer_message_destroy
        delete 'teacher/:teacher_id', :action => :destroy, :as => :teacher_observer_message_destroy
      end
      collection do
        get "draft"
        get "sent"
        post "destroy_all_data"
        get "student/:student_id/sent", :action => :sent, :as => :student_observer_message_sent
        get "teacher/:teacher_id/sent", :action => :sent, :as => :teacher_observer_message_sent
        get "student/:student_id", :action => :index, :as => :student_observer_message_inbox
        get "teacher/:teacher_id", :action => :index, :as => :teacher_observer_message_inbox
        get "student/:student_id/new", :action => :new, :as => :student_observer_message_new
        get "teacher/:teacher_id/new", :action => :new, :as => :teacher_observer_message_new
        post "student/:student_id", :action => :create, :as => :student_observer_message_create
        post "teacher/:teacher_id", :action => :create, :as => :teacher_observer_message_create
      end
    end

    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    match "messages/inbox_detail/:id"=> "messages#inbox_detail", :as => :inbox_detail, :via => :get
    
    match "messages/sent_detail/:id"=> "messages#sent_detail", :as => :sent_detail, :via => :get
    match "messages/sent_detail/:id/student/:student_id"=> "messages#sent_detail", :as => :student_observer_sent_detail, :via => :get
    match "messages/sent_detail/:id/teacher/:teacher_id"=> "messages#sent_detail", :as => :teacher_observer_sent_detail, :via => :get
    
    match "messages/draft_detail/:id"=> "messages#draft_detail", :as => :draft_detail, :via => :get

    resources :assignments do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_assignment
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_assignment
        get "download"
        put "remove_file"
        get "edit_assignment_category", :action => "edit_assignment_category", :as => :edit_assignment_category
        put "update_assignment_category", :action => "update_assignment_category", :as => :update_assignment_category
        delete "delete_assignment_category", :action => "delete_assignment_category", :as => :delete_assignment_category
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_assignments_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_assignments_index
        get "assignment_category", :action => "assignment_category", :as => :assignment_category
        post "create_assignment_category", :action => "create_assignment_category", :as => :create_assignment_category
        get "new_assignment_category", :action => "new_assignment_category", :as => :new_assignment_category

      end

      resources :writeboards
    end

    resources :writeboards do
      
      member do
        post "comment_create"
        get "comment_edit/:comment_id", :action => "comment_edit", :as => :edit_writeboard_assignment
        delete "comment_destroy/:comment_id", :action => "comment_destroy", :as => :destroy_writeboard_comment
        put "comment_update/:comment_id", :action => "comment_update", :as => :update_writeboard_comment
        get "vote_up"
      end
      
      collection do
        get "student/:student_id", :action => "index", :as => :student_writeboards_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_writeboards_index
      end
    end

    match "/assignments/:id/comment_edit/:comment_id" => "assignments#comment_edit", :as => :comment_edit_assignment, :via => :get
    match "/assignments/:id/comment_update/:comment_id" => "assignments#comment_update", :as => :comment_update_assignment, :via => :put
    match "/assignments/:id/comment_destroy/:comment_id" => "assignments#comment_destroy", :as => :comment_destroy_assignment, :via => :delete

    match "/events/:id/comment_edit/:comment_id" => "calendar#comment_edit", :as => :comment_edit_event, :via => :get
    match "/events/:id/comment_update/:comment_id" => "calendar#comment_update", :as => :comment_update_event, :via => :put
    match "/events/:id/comment_destroy/:comment_id" => "calendar#comment_destroy", :as => :comment_destroy_event, :via => :delete

    match "/upload_files/:id/comment_edit/:comment_id" => "upload_files#comment_edit", :as => :comment_edit_upload_files, :via => :get
    match "/upload_files/:id/comment_update/:comment_id" => "upload_files#comment_update", :as => :comment_update_upload_files, :via => :put
    match "/upload_files/:id/comment_destroy/:comment_id" => "upload_files#comment_destroy", :as => :comment_destroy_upload_files, :via => :delete

    resources :calendar, :except => [:index, :create, :update]

    resources :events, :controller => :calendar do
      member do
        post "comment_create"
        get "download"
        put "remove_file"
      end
    end

    resources :people do
      collection do
        post "add_person_from_existing_people"
      end

      member do
        delete "remove_from_class"
      end
    end

    match "/notes/:id/comment_edit/:comment_id" => "notes#comment_edit", :as => :comment_edit_notes, :via => :get
    match "/notes/:id/comment_update/:comment_id" => "notes#comment_update", :as => :comment_update_notes, :via => :put
    match "/notes/:id/comment_destroy/:comment_id" => "notes#comment_destroy", :as => :comment_destroy_notes, :via => :delete

   
    resources :discussions do
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_discussion
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_discussion
        get "download"
        put "remove_file"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_discussion_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_discussion_index
      end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_my_students_and_class
  
  def index
    @inboxes = current_user.received_messages
    @files = MessageFile.where("user_id =?",current_user.id)
  end

  def sent
    @sent_mails = current_user.sent_messages
  end

  def edit
    @message = current_user.messages.with_id(params[:id]).first
    @users = User.all
  end
  
  def sent_detail
    @sent_detail = current_user.sent_messages
    @message_id = params[:id]
  end
  
  def update
    @sender = current_user
    
    if params[:chk_ids].nil?
      @sender.send_message(current_user ,params[:acts_as_messageable_message][:topic],params[:acts_as_messageable_message][:body])
    else
      @receivers = params[:chk_ids]
      @receivers.each do |receiver|
        @receiver = User.find(receiver)
        @sender.send_message(@receiver ,params[:acts_as_messageable_message][:topic],params[:acts_as_messageable_message][:body])
      end
    end
    
    redirect_to(class_room_messages_url)
  end

  def destroy
    @message = current_user.messages.with_id(params[:id]).first
    @message.destroy
    
    if params[:student_id]
      redirect_to student_observer_message_inbox_class_room_messages_url(@class, params[:student_id])
    elsif params[:teacher_id]
      redirect_to teacher_observer_message_inbox_class_room_messages_url(@class, params[:teacher_id])
    else
      redirect_to(class_room_messages_url)
    end
  end

  def new
    if current_user.is_teacher?
      @users = @students + @class.observers
    elsif current_user.is_student?
      @users = User.where("roles=?",[['teacher']])
    else
      @users = User.where("roles=?",[['teacher']])
    end
  end

  def create
    @sender = current_user
    unless (current_user.is_student? or current_user.is_observer?)
      if params[:chk_ids].nil?
        redirect_to :back
      else
        @receivers = params[:chk_ids]
        @file = params[:message][:file]
        @receivers.each do |receiver|
          @receiver = User.find(receiver)
          @sender.send_message(@receiver ,params[:message][:topic],params[:message][:body])
          unless params[:message][:file].nil?
            message_id = current_user.messages.are_to(receiver).last.id
            @message_file = MessageFile.create(:file => @file,:message_id =>message_id,:user_id =>receiver)
            @message_file.save
          end
        end
      end
    else
      @sender.send_message(@class.user, params[:message][:topic], params[:message][:body])
    end
    if params[:student_id]
      redirect_to(student_observer_message_inbox_class_room_messages_url(@class.id, params[:student_id]), notice: 'Message has been sent')
    elsif params[:teacher_id]
      redirect_to(teacher_observer_message_inbox_class_room_messages_url(@class.id, params[:teacher_id]), notice: 'Message has been sent')
    elsif current_user.is_teacher? or current_user.is_student?
      redirect_to(class_room_messages_url(@class.id), notice: 'Message has been sent')
    else
      redirect_to :back
    end
  end
  
  def draft
    @drafts = current_user.sent_messages
  end
  
  def draft_detail
    @draft_detail = current_user.sent_messages
    @message_id = params[:id]
  end
  
  def inbox_detail
    @message_id = params[:id]
    @inbox_detail = current_user.messages.where('id=?',@message_id).first
    @inbox_detail.opened = 1
    @inbox_detail.save
  end

  def edit_draft
  end
  
  def destroy_all_data
    @destroy_data = params[:chk_ids]
    
    @destroy_data.each do |inbox|
      @delete=current_user.messages.find(inbox)
      @delete.recipient_delete=1
      @delete.save
    end
    
    redirect_to(class_room_url(@class.id),:notice =>'.delete')
  end

  def download
    file = MessageFile.find(params[:id])
    send_file file.file.path, :type => file.file_content_type
  end

  private

  def get_my_students_and_class
    @class = if current_user.is_teacher?
      current_user.class_rooms.find(params[:class_room_id])
    elsif current_user.is_student?
      my_class_room = current_user.class_room_students.where(class_room_id: params[:class_room_id]).first
      my_class_room.class_room if my_class_room
    elsif current_user.is_observer?
      if params[:student_id]
        @student = User.find params[:student_id]
        student_class_room = @student.class_room_students.where(class_room_id: params[:class_room_id]).first
        student_class_room.class_room if student_class_room
      elsif params[:teacher_id]
        @teacher = User.find params[:teacher_id]
        ClassRoom.find params[:class_room_id]
      end
    end
    @students = @class.students
  end
 
end

app/helpers/messages_helper.rb
module MessagesHelper
  def users_first_name(x)
    User.where("id = ?",x).first
  end
 
  def message_receiver(receive)
    User.where("id=?",receive)
  end

 def user_sender(sender_id)
   User.where("id=?",sender_id)
 end
  
  def user_sender(sender_id)
    User.where("id=?",sender_id)
  end

 def user_sender(sender_id)
   User.where("id=?",sender_id)
 end

end

app/views/messages/create.html.haml
%h1 Messages#create
%p Find me in app/views/messages/create.html.haml

app/views/messages/delete.html.haml
%h1 Messages#delete
%p Find me in app/views/messages/delete.html.haml

app/views/messages/draft.html.haml
/- content_for :middle_content do
%h3 All Draft
%table{:border=>'1',:width=>'400'}
  -@drafts.each do |draft|
    %tr
      -if draft.received_messageable_id.eql?(current_user.id)
        %td Draft
        %td
          -if draft.topic.nil?
            ='(no subject)'
          -else
            %b
              = '('
              = draft.topic
              = ')'
              = '-'
          =link_to truncate(strip_tags(draft.body), :length => 80),class_room_draft_detail_path(@class.id,draft.id)
          =link_to 'Edit message',edit_class_room_message_path(@class.id,draft)
          =link_to 'Delete',class_room_message_path(@class.id,draft),:confirm => 'Are you sure?', :method => :delete
%center
  ='New Draft'
  = form_tag class_room_messages_path do
    = hidden_field_tag 'message[receiver]'
    = label_tag 'Title :'
    = text_field_tag 'message[topic]', nil, :placeholder => 'Enter the subject'
    %br
    = label_tag 'Body :'
    = text_area_tag 'message[body]', nil,:size => "25x10"
    %br
    = submit_tag "Save"
          

app/views/messages/draft_detail.html.haml
/- content_for :middle_content do
-@draft_detail.each do |draft|
  -if draft.id.eql?(@message_id.to_i)

    %br

    %br
      %b
        ='Topic :'
      =draft.topic
    %br
      %b
        ='Description:'
    %br
      =draft.body

app/views/messages/edit.html.haml
/- content_for :middle_content do
= form_for @message, :url => class_room_message_path(@class.id, @message), :method => :put do |f|
  -if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this discussion from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :topic
    %br/
    = f.text_field :topic
  .field
    = f.label :body
    %br/
    = f.text_area :body
    = f.hidden_field :user_id,:value=>current_user.id

    %table{:border=>'1'}
      %tr
        %td
          ='Receiver(s)'
          %input#Check_ctr{:name => "Check_ctr", :onClick => "Check();", :type => "checkbox"}
      - @counter = 0
      -@users.each do |user|
        - @counter += 1
        -unless current_user.id.eql?(user.id)
          %tr
            %td
              =user.first_name
              %input{:id => "chk_id#{@counter}", :name => "chk_ids[]", :type => "checkbox", :value => user.id, :class =>'check_msg',:onclick => "$('#Check_ctr').attr('checked', false)"}
    %input#ttl{:type => "hidden", :value => "#{@counter} "}
   
  .actions
    = f.submit 'Save'

app/views/messages/inbox_detail.html.haml
/- content_for :middle_content do
%br
%b
  ='From:'
='me'
%p
  %b Subject
=@inbox_detail.topic
%p
  %b Description
=@inbox_detail.body

app/views/messages/index.html.haml
/- content_for :middle_content do
%br
%br
%div#notice= notice
%div#notice= alert
%h2 Private Message
- unless current_user.is_observer?
  = link_to 'New message', new_class_room_message_path(@class.id)
- else
  - if @student
    = link_to 'New message', student_observer_message_new_class_room_messages_path(@class.id, @student.id)
  - elsif @teacher
    = link_to 'New message', teacher_observer_message_new_class_room_messages_path(@class.id, @teacher.id)
%br
- unless current_user.is_observer?
  = link_to 'Sent mail', sent_class_room_messages_path(@class.id)
- else
  - if @student
    = link_to "Sent mail", student_observer_message_sent_class_room_messages_path(@class.id, @student.id)
  - elsif @teacher
    = link_to "Sent mail", teacher_observer_message_sent_class_room_messages_path(@class.id, @teacher.id)
/%br
/= link_to 'Draft', draft_class_room_messages_path(@class.id)
= form_tag destroy_all_data_class_room_messages_path(@class.id) do
  %p inbox
  %table{:border=>'1',:width=>'400'}
    %tr
    %td
      %b From
    %td
      %b Subject
    %td
      %b Description
    %td
      %b Sent at
    %td
      %b File
    %td
      %b Delete
      %input#Check_ctr{:name => "Check_ctr", :onClick => "Check();", :type => "checkbox"}
      - @counter = 0
    -@inboxes.each do |inbox|
      
      -if inbox.sent_messageable_id.eql?(current_user.id)
        -true
      -else
        - @counter += 1
        %tr

          %td
            -if current_user.messages.find(inbox.id).opened
              -user_sender(inbox.sent_messageable_id).each do |sender|
                = user_full_name(sender)
            -else
              %b
                -user_sender(inbox.sent_messageable_id).each do |sender|
                  = user_full_name(sender)

          %td
            -if current_user.messages.find(inbox.id).opened
              = inbox.topic
            -else
              %b
                =inbox.topic
          %td
            -if current_user.messages.find(inbox.id).opened
              - if params[:student_id]
                =link_to truncate(strip_tags(inbox.body), :length => 80), student_inbox_detail_observer_class_room_message_path(@class.id, inbox.id, "#{params[:student_id]}")
              - elsif params[:teacher_id]
                =link_to truncate(strip_tags(inbox.body), :length => 80), teacher_inbox_detail_observer_class_room_message_path(@class.id, inbox.id, "#{params[:teacher_id]}")
              - else
                =link_to truncate(strip_tags(inbox.body), :length => 80), class_room_inbox_detail_path(@class.id, inbox.id)

            -else
              %b
                - if params[:student_id]
                  =link_to truncate(strip_tags(inbox.body), :length => 80), student_inbox_detail_observer_class_room_message_path(@class.id, inbox.id, "#{params[:student_id]}")
                - elsif params[:teacher_id]
                  =link_to truncate(strip_tags(inbox.body), :length => 80), teacher_inbox_detail_observer_class_room_message_path(@class.id, inbox.id, "#{params[:teacher_id]}")
                - else
                  =link_to truncate(strip_tags(inbox.body), :length => 80), class_room_inbox_detail_path(@class.id, inbox.id)

          %td
            -if current_user.messages.find(inbox.id).opened
              =date_format(inbox.created_at)
            -else
              %b
                =date_format(inbox.created_at)
          %td
            -unless file(inbox.id).nil?
              =link_to file(inbox.id).file_file_name,download_class_room_message_path(@class.id, file(inbox.id).id)
          %td{:align => "right"}
            %input{:id => "chk_id#{@counter}", :name => "chk_ids[]", :type => "checkbox", :value => inbox.id, :class =>'check_msg',:onclick => "$('#Check_ctr').attr('checked', false)"}
    %input#ttl{:type => "hidden", :value => "#{@counter} "}
    =submit_tag 'Delete'
%br
%br

app/views/messages/new.html.haml
/- content_for :middle_content do
%br
%br
%center
  - if current_user.is_teacher?
    = form_tag class_room_messages_path(@class.id),:name =>'form1',:multipart =>true do
      = hidden_field_tag 'teacher_id',current_user.id
      = label_tag 'Title :'
      = text_field_tag 'message[topic]', nil, :placeholder => 'Enter the subject'
      %br
      = label_tag 'Body :'
      = text_area_tag 'message[body]', nil, :size => "25x10"
      %br
      = label_tag 'File :'
      = file_field_tag 'message[file]'
      %br
      %table{:border=>'1'}
        %tr
          %td{:align => "center"}
            ='Send to all'
            %input#Check_ctr{:name => "Check_ctr", :onClick => "Check();", :type => "checkbox"}
        - counter = 0
        - @users.each do |user|
          - counter += 1
          - unless current_user.id.eql?(user.id) and user.is_observer?
            %tr
              %td
                =user.first_name
                %input{:id => "chk_id#{@counter}", :name => "chk_ids[]", :type => "checkbox",  :value => user.id, :class =>'check_msg',:onclick => "$('#Check_ctr').attr('checked', false)"}

      %input#ttl{:type => "hidden", :value => "#{counter} "}
      = submit_tag "Save",:onclick=>"return checkField()"
  - elsif current_user.is_observer?
    - if @student
      = form_tag student_observer_message_create_class_room_messages_path(@class.id, @student.id),:multipart =>true  do

        = label_tag 'Title :'
        = text_field_tag 'message[topic]', nil, :placeholder => 'Enter the subject'
        %br
        = label_tag 'Body :'
        = text_area_tag 'message[body]', nil, :size => "25x10"
        %br
        = label_tag 'File :'
        = file_field_tag 'message[file]'
        %br
        = submit_tag "Send", :onclick =>'return checkFieldStudentAndObserver()'
    - elsif @teacher
      = form_tag teacher_observer_message_create_class_room_messages_path(@class.id, @teacher.id),:multipart =>true  do

        = label_tag 'Title :'
        = text_field_tag 'message[topic]', nil, :placeholder => 'Enter the subject'
        %br
        = label_tag 'Body :'
        = text_area_tag 'message[body]', nil, :size => "25x10"
        %br
        = label_tag 'File :'
        = file_field_tag 'message[file]'
        %br
        = submit_tag "Save", :onclick =>'return checkFieldStudentAndObserver()'
  - else
    = form_tag class_room_messages_path(@class.id),:multipart =>true  do

      = label_tag 'Title :'
      = text_field_tag 'message[topic]', nil, :placeholder => 'Enter the subject'
      %br
      = label_tag 'Body :'
      = text_area_tag 'message[body]', nil, :size => "25x10"
      %br
      = label_tag 'File :'
      = file_field_tag 'message[file]'
      %br
      = submit_tag "Send", :onclick =>'return checkFieldStudentAndObserver()'

app/views/messages/sent.html.haml
/- content_for :middle_content do
%h1 Sent Messages
%table{:border=>'1'}
  %tr
    %td
      %b Mail To
    %td
      %b Subject
    %td
      %b Sent at
    %td
      %b Delete
  -@sent_mails.each do |sent|
    -if sent.received_messageable_id.nil?
      -true
    -else
      -if sent.received_messageable_id.eql?(current_user.id)
        -false
      -else
        %tr
          %td
            - user = users_first_name(sent.received_messageable_id)
            - if user
              - if @student
                =link_to user_full_name(user), class_room_student_observer_sent_detail_path(@class.id, sent.id, @student.id)
              - elsif @teacher
                =link_to user_full_name(user), class_room_teacher_observer_sent_detail_path(@class.id, sent.id, @teacher.id)
              - else
                =link_to user_full_name(user), class_room_sent_detail_path(@class.id,sent.id)
          %td
            = sent.body
          %td
            = date_format(sent.created_at)
          %td
            - if @student
              = link_to 'Delete', student_observer_message_destroy_class_room_message_path(@class.id, sent, @student.id),:confirm => 'Are you sure?', :method => :delete
            - elsif @teacher
              = link_to 'Delete', teacher_observer_message_destroy_class_room_message_path(@class.id, sent, @teacher.id),:confirm => 'Are you sure?', :method => :delete
            - else
              = link_to 'Delete', class_room_message_path(@class.id,sent),:confirm => 'Are you sure?', :method => :delete

app/views/messages/sent_detail.html.haml
/- content_for :middle_content do
%br
-@sent_detail.each do |detail|
  -if detail.id.eql?(@message_id.to_i)
    %b
      = 'From :'
    = 'me'
    %br
    %b 'To'
    -user_sender(detail.received_messageable_id).each do |sender|
      = user_full_name(sender)
    %br
    %br
      =detail.topic
    %br
    %br
      =detail.body
    

  

app/views/messages/update.html.haml
%h1 Messages#update
%p Find me in app/views/messages/update.html.haml