config/routes.rb
Tes::Application.routes.draw do
  resources :user_meeting_rooms

  resources :meeting_rooms do
    get "user",:on =>:collection
    get "moderator", :on =>:member
    put "add_moderator", :on =>:member
    member do
      get "comment_new"
      post "comment_create"
    end
  end
  match "meeting_rooms/:id/comment_edit/:comment_id"=> "meeting_rooms#comment_edit", :as => :edit_meeting_room_comment, :via => :get
  match "meeting_rooms/:id/comment_update/:comment_id"=> "meeting_rooms#comment_update", :as => :update_meeting_room_comment, :via => :put
  match "meeting_rooms/:id/comment_destroy/:comment_id"=> "meeting_rooms#comment_destroy", :as => :destroy_meeting_room_comment, :via => :delete

  resources :states do
    get :autocomplete_state_name, :on => :collection
  end
  get "admins/index"

  get "pages/index"

  match "pages/city/:city"=> "pages#city", :as => :state_city, :via => :get
  match "pages/school/:school"=> "pages#school", :as => :school_city, :via => :get
  match "pages/search_state/"=> "pages#search_state", :as => :search_state, :via => :get
  match "pages/country/"=> "pages#country", :as => :country, :via => :get
  match "pages/city_list/:country_id"=> "pages#city_list", :as => :city_list, :via => :get
  match "pages/states_list/"=> "pages#state_list", :as => :state_list, :via => :get

  namespace :admin do

    resources :admins do
      member do
        put "update"
        get "edit_school"
        put "update_school"
      end
      collection do
        get "school"
        get "new_school"
        post "create_school"
      end

    end

  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" } do
    get "welcome"=> "devise/registrations#index", :as => :welcome
  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
    match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
  end

  resources :activity_stream_preferences
  resources :activity_streams
  resources :class_rooms do

    match "reply/:comment_id"=> "comments#reply", :as => :reply_comment, :via => :post

    match "voteable_type/:id/comment_vote/:comment_id"=> "comments#index", :as => :comment_vote, :via => :get
    match "user_profiles/:student_id"=> "user_profiles#index", :as => :user_profile, :via => :get
    devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
      match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
    end

    resources :upload_files do

      member do
        get "comment_new"
        post "comment_create"
        
        get "student/:student_id", :action => "show", :as => :show_student_upload_file
        get "teacher/:teacher_id", :action => "show", :as => :show_teacher_upload_file
        get "comment_student/:student_id", :action => "comment_new", :as => :go_to_student_upload_file
        get "comment_teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_upload_file
      end
      
      collection do
        get "download"
        get "student/:student_id", :action => "index", :as => :student_upload_files_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_upload_files_index
      end
      
    end

    resources :notes do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_note
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_note
        get "download"
        put "remove_file"
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_notes_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_notes_index
      end
    end
    
    resources :to_dos do
      collection do
        get "selected_time"
      end
    end

    resources :messages do
      member do
        get "student/:student_id", :action => "inbox_detail", :as => :student_inbox_detail_observer
        get "teacher/:teacher_id", :action => "inbox_detail", :as => :teacher_inbox_detail_observer

        get "download"
        get "edit_draft"
        post 'delete_draft'
        delete 'student/:student_id', :action => :destroy, :as => :student_observer_message_destroy
        delete 'teacher/:teacher_id', :action => :destroy, :as => :teacher_observer_message_destroy
      end
      collection do
        get "draft"
        get "sent"
        post "destroy_all_data"
        get "student/:student_id/sent", :action => :sent, :as => :student_observer_message_sent
        get "teacher/:teacher_id/sent", :action => :sent, :as => :teacher_observer_message_sent
        get "student/:student_id", :action => :index, :as => :student_observer_message_inbox
        get "teacher/:teacher_id", :action => :index, :as => :teacher_observer_message_inbox
        get "student/:student_id/new", :action => :new, :as => :student_observer_message_new
        get "teacher/:teacher_id/new", :action => :new, :as => :teacher_observer_message_new
        post "student/:student_id", :action => :create, :as => :student_observer_message_create
        post "teacher/:teacher_id", :action => :create, :as => :teacher_observer_message_create
      end
    end

    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    match "messages/inbox_detail/:id"=> "messages#inbox_detail", :as => :inbox_detail, :via => :get
    
    match "messages/sent_detail/:id"=> "messages#sent_detail", :as => :sent_detail, :via => :get
    match "messages/sent_detail/:id/student/:student_id"=> "messages#sent_detail", :as => :student_observer_sent_detail, :via => :get
    match "messages/sent_detail/:id/teacher/:teacher_id"=> "messages#sent_detail", :as => :teacher_observer_sent_detail, :via => :get
    
    match "messages/draft_detail/:id"=> "messages#draft_detail", :as => :draft_detail, :via => :get

    resources :assignments do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_assignment
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_assignment
        get "download"
        put "remove_file"
        get "edit_assignment_category", :action => "edit_assignment_category", :as => :edit_assignment_category
        put "update_assignment_category", :action => "update_assignment_category", :as => :update_assignment_category
        delete "delete_assignment_category", :action => "delete_assignment_category", :as => :delete_assignment_category
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_assignments_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_assignments_index
        get "assignment_category", :action => "assignment_category", :as => :assignment_category
        post "create_assignment_category", :action => "create_assignment_category", :as => :create_assignment_category
        get "new_assignment_category", :action => "new_assignment_category", :as => :new_assignment_category

      end

      resources :writeboards
    end

    resources :writeboards do
      
      member do
        post "comment_create"
        get "comment_edit/:comment_id", :action => "comment_edit", :as => :edit_writeboard_assignment
        delete "comment_destroy/:comment_id", :action => "comment_destroy", :as => :destroy_writeboard_comment
        put "comment_update/:comment_id", :action => "comment_update", :as => :update_writeboard_comment
        get "vote_up"
      end
      
      collection do
        get "student/:student_id", :action => "index", :as => :student_writeboards_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_writeboards_index
      end
    end

    match "/assignments/:id/comment_edit/:comment_id" => "assignments#comment_edit", :as => :comment_edit_assignment, :via => :get
    match "/assignments/:id/comment_update/:comment_id" => "assignments#comment_update", :as => :comment_update_assignment, :via => :put
    match "/assignments/:id/comment_destroy/:comment_id" => "assignments#comment_destroy", :as => :comment_destroy_assignment, :via => :delete

    match "/events/:id/comment_edit/:comment_id" => "calendar#comment_edit", :as => :comment_edit_event, :via => :get
    match "/events/:id/comment_update/:comment_id" => "calendar#comment_update", :as => :comment_update_event, :via => :put
    match "/events/:id/comment_destroy/:comment_id" => "calendar#comment_destroy", :as => :comment_destroy_event, :via => :delete

    match "/upload_files/:id/comment_edit/:comment_id" => "upload_files#comment_edit", :as => :comment_edit_upload_files, :via => :get
    match "/upload_files/:id/comment_update/:comment_id" => "upload_files#comment_update", :as => :comment_update_upload_files, :via => :put
    match "/upload_files/:id/comment_destroy/:comment_id" => "upload_files#comment_destroy", :as => :comment_destroy_upload_files, :via => :delete

    resources :calendar, :except => [:index, :create, :update]

    resources :events, :controller => :calendar do
      member do
        post "comment_create"
        get "download"
        put "remove_file"
      end
    end

    resources :people do
      collection do
        post "add_person_from_existing_people"
      end

      member do
        delete "remove_from_class"
      end
    end

    match "/notes/:id/comment_edit/:comment_id" => "notes#comment_edit", :as => :comment_edit_notes, :via => :get
    match "/notes/:id/comment_update/:comment_id" => "notes#comment_update", :as => :comment_update_notes, :via => :put
    match "/notes/:id/comment_destroy/:comment_id" => "notes#comment_destroy", :as => :comment_destroy_notes, :via => :delete

   

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_commentable
  acts_as_textiled :description

  belongs_to :user
  belongs_to :class_room
  
  validates :title, :description, :user_id, :class_room_id, :presence => true
  validates :title, :uniqueness => {:scope => [:user_id, :class_room_id]}

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  log_activity_streams :current_user, :full_name, :commented,
    :@note, :title, :comment_create, :note

  before_filter :authenticate_user!
  before_filter :get_my_students_and_class

  def index
    @notes = @class.notes
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(params[:note])
    @note.class_room_id = @class.id

    if @note.save
      redirect_to class_room_notes_url(@class.id), notice: 'Note was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @note = Note.find(params[:id])

    if @note.update_attributes(params[:note])
      redirect_to class_room_notes_url(@class.id), notice: 'Note was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    
    redirect_to(class_room_notes_url(@class.id))
  end
  
  def comment_new
    @note = Note.find(params[:id])
    @replies = Reply.all
  end

  def comment_create
    @note = Note.find(params[:id])
    @note.comments.create(params[:comment])
    
    redirect_to comment_new_class_room_note_url(@class, params[:id])
  end
    

  def comment_destroy
    @note = Note.find(params[:id])
    comment = @note.comments.find(params[:comment_id])
    comment.destroy if comment
    
    redirect_to comment_new_class_room_note_url(@class, params[:id])
  end

  def comment_edit
    @note = Note.find(params[:id])
    @comment = @note.comments.find(params[:comment_id])
  end

  def comment_update
    @note = Note.find(params[:id])
    @comment = @note.comments.find(params[:comment_id])
    if params[:comment][:file].nil?
      params[:comment][:file] = @comment.file.path
    else
      params[:comment][:file]
    end
    
    if @comment.update_attributes(params[:comment])
      redirect_to comment_new_class_room_note_url(@class, params[:id])
    else
      render :action => "comment_edit"
    end
  end

  def download
    file = Comment.find(params[:id])
    send_file file.file.path, :type => file.file_content_type
  end

  def remove_file
    file = Comment.find(params[:id])
    
    if file.update_attributes(:file_updated_at =>'')
      redirect_to class_room_notes_url(@class.id)
    else
      render :action => "comment_edit"
    end
  end

  def vote_up
    post = Note.find(params[:id])
    current_user.vote_for(post)

    redirect_to class_room_notes_url(@class.id) 
  end

  private

  def get_my_students_and_class
    @class = if current_user.is_teacher?
      current_user.class_rooms.find(params[:class_room_id])
    elsif current_user.is_student?
      my_class_room = current_user.class_room_students.where(class_room_id: params[:class_room_id]).first
      my_class_room.class_room
    elsif current_user.is_observer?
      if params[:student_id]
        @student = User.find params[:student_id]
        student_class_room = @student.class_room_students.where(class_room_id: params[:class_room_id]).first
        student_class_room.class_room if student_class_room
      elsif params[:teacher_id]
        @teacher = User.find params[:teacher_id]
        ClassRoom.find params[:class_room_id]
      end
    end
    @students = @class.students
  end
  
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
- if @note.new_record?
  = form_for @note, :url => class_room_notes_path(@class.id) do |f|
    -if @note.errors.any?
      #error_explanation
        %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
        %ul
          - @note.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_field :title, :placeholder => "Enter a title"
    .field
      %br/
      = f.text_area :description, :rows => 36, :cols => 100, :placeholder => "Remember, you can use Textile to format the text. See the bottom of the page for instructions!"
      = f.hidden_field :user_id,:value => current_user.id
    .actions
      = f.submit 'Save'
- else
  = form_for @note, :url => class_room_note_path(@class.id, @note) do |f|
    -if @note.errors.any?
      #error_explanation
        %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
        %ul
          - @note.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_field :title, :placeholder => "Enter a title"
    .field
      %br/
      = f.text_area :description, :rows => 36, :cols => 100, :placeholder => "Remember, you can use Textile to format the text. See the bottom of the page for instructions!"
      = f.hidden_field :user_id,:value => current_user.id
    .actions
      = f.submit 'Save'

app/views/notes/comment_edit.html.haml
%table{:width => "50%"}
  -if current_user.is_teacher? and !current_user.class_rooms.blank?
    %tr
      %td
        %b= @note.title
      %td{:align => "right"}
        = link_to "New", new_class_room_note_path(@class.id)
        | #{link_to "Edit", edit_class_room_note_path(@class.id, @note)} | #{link_to "Delete", class_room_note_path(@class.id, @note)}
  -else
    -true
  %tr
    %td{:colspan => "2"}
      From: #{user_full_name(@note.user)}
      - unless vote_count(@note.id).eql?(0) or current_user.is_teacher?
        = '('
        = vote_count(@note.id)
        = ')'
  %tr
    %td{:colspan => "2"}
      Date: #{date_format(@note.created_at)}

  %tr
    %td{:colspan => "2"}
      %hr{:noshade => ""}
  %tr
    %td{:colspan => "2"}
      = @note.description
  %tr
    %td{:colspan => "2"}
      %hr{:noshade => ""}
  %tr
    %td{:colspan => "3"}
      #comments_container
        - @note.comments.each do |comment|
          %table{:width => "100%"}
            %tr
              %td{:rowspan => "3"}= image_tag "bakso.jpg", :width => "48", :height => "48"
              %td{:colspan => "3"}
                = "#{user_full_name(comment.user)}"
                - unless vote_count(comment.id).eql?(0) or !current_user.is_teacher?
                  = "(#{vote_count(comment.id)})"
                = "#{date_format(comment.created_at)}"
            %tr
              %td
                = comment.comment
                - unless comment.file_updated_at.nil?
                  %br
                  = 'file :'
                  - if current_user.is_observer?
                    = comment.file_file_name
                  - elsif current_user.id.eql?(comment.user_id) or current_user.is_teacher?
                    = link_to comment.file_file_name, download_class_room_note_path(@class.id, comment.id)
                    | #{link_to 'remove',remove_file_class_room_note_path(@class.id, comment.id), :confirm => "Are you sure ?", :method => :put}
              %td{:align => "right"}
                - if current_user.id.eql?(comment.user_id)
                  = link_to "Edit", class_room_comment_edit_notes_path(@class.id, @note, comment.id)
                  | #{link_to "Delete", class_room_comment_destroy_notes_path(@class.id, @note, comment.id), :method => :delete}
                - unless vote_comment(comment).nil?
                  = 'Wee!!'
                - else
                  = link_to 'Weee!!',class_room_comment_vote_path(@class.id ,@note.id,comment,:commentable_type =>"#{params[:controller]}")
                - if current_user.id.eql?(@note.user_id) and !current_user.id.eql?(comment.user_id) and comment.replies.count.eql?(0)
                  = link_to 'Reply', '#',:onclick => "$('.reply_#{comment.id}').show()"
                  %div{:class =>"reply_#{comment.id}", :style=> "display: none;"}
                    %h1=link_to 'x','#',:onclick => "$('.reply_#{comment.id}').hide()"
                    = form_tag(class_room_reply_comment_path(@class.id, comment.id), :multipart => true)   do |f|
                      .field
                        = text_area_tag "reply[body]", nil, :rows => 4, :cols => 40
                        = hidden_field_tag 'reply[user_id]',comment.user_id
                        = hidden_field_tag 'reply[replier_id]',current_user.id
                        = hidden_field_tag 'reply[comment_id]',comment.id
                        = hidden_field_tag 'comment_controller',"#{params[:controller]}"
                        = hidden_field_tag 'id',"#{params[:id]}"
                      .actions
                        = submit_tag "Add this Comment"
            - comment.replies.each do |reply|
              %tr
                %td{:style =>"text-align:center;",:bgcolor=>'red'}
                  %h1="This is a reply: #{reply.body}"
            %tr
              %td{:colspan => "3"}
                %hr{:noshade => ""}
                  #upload{:style=> "display: none;"}
                    = form_tag(class_room_comment_update_notes_path(@class.id, @note,comment.id),:method =>:put)do
                      .field
                        = file_field_tag "file"
                        = hidden_field_tag "comment[comment]",comment.comment
                        = hidden_field_tag "comment[user_id]",comment.user_id
                        = submit_tag "Submit"
%h1 Update comement
= form_tag(class_room_comment_update_notes_path(@class.id, @note, @comment.id), :method => :put, :multipart =>true) do |f|
  .field
    = text_area_tag "comment[comment]", @comment.comment, :rows => 4, :cols => 40
    %br
    = file_field_tag "comment[file]"
  .actions
    = submit_tag "update this Comment"

app/views/notes/comment_new.html.haml
.standard_text
  %h3 Posted #{distance_of_time_in_words(@note.created_at, Time.now)} ago
  %hr
  -if current_user.id.eql?(@note.user_id)
    #{link_to "Edit", edit_class_room_note_path(@class.id, @note)} | #{link_to "Delete", class_room_note_path(@class.id, @note), :confirm => "Are you sure ?", :method => :delete}
  %td
    %br
      
  -else
    -true
    #user_content
      .user_titles
        %h1
          = @note.title
      .textile
        %p
          != @note.description
    %br
  %tr
    %hr
    %hr
  %tr
    %td{:colspan => "3"} 
      #comments_container
        %h4 Comments
        %br
        - @note.comments.each do |comment| 
          %table{:width => "100%"}
            %tr
              %h6{:colspan => "3"}
                = "#{user_full_name(comment.user)}"
                - unless vote_count(comment.id).eql?(0) or current_user.is_teacher?
                  = "(#{vote_count(comment.id)})"
                said this #{distance_of_time_in_words(comment.created_at, Time.now)} ago:
            %tr
            %br
            %h4
              = comment.comment
              %td{:align => "right"}
                %div{:id=>"comment"+comment.id.to_s}
                  - if current_user.id.eql?(comment.user_id)
                    = link_to "Edit", class_room_comment_edit_notes_path(@class.id, @note, comment.id)
                    #{link_to "Delete", class_room_comment_destroy_notes_path(@class.id, @note, comment.id), :method => :delete}
                  - elsif current_user.id.eql?(comment.user_id) or current_user.is_teacher?
                    = link_to "Delete", class_room_comment_destroy_notes_path(@class.id, @note, comment.id), :method => :delete
                  - unless vote_comment(comment).nil?
                    = image_tag('supercool_button_grey.png')
                  - else
                    = link_to image_tag('supercool_button.png'),class_room_comment_vote_path(@class.id ,@note.id,comment,:commentable_type =>"#{params[:controller]}")
                  - if current_user.id.eql?(@note.user_id) and !current_user.id.eql?(comment.user_id) and comment.replies.count.eql?(0)
                    = link_to 'Reply', '#',:onclick => "$('.reply_#{comment.id}').show()"
                    %div{:class =>"reply_#{comment.id}", :style=> "display: none;"}
                      %h1=link_to 'x','#',:onclick => "$('.reply_#{comment.id}').hide()"
                      = form_tag(class_room_reply_comment_path(@class.id, comment.id), :multipart => true)   do |f|
                        .field
                          = text_area_tag "reply[body]", nil, :rows => 4, :cols => 40
                          = hidden_field_tag 'reply[user_id]',comment.user_id
                          = hidden_field_tag 'reply[replier_id]',current_user.id
                          = hidden_field_tag 'reply[comment_id]',comment.id
                          = hidden_field_tag 'comment_controller',"#{params[:controller]}"
                          = hidden_field_tag 'id',"#{params[:id]}"
                        .actions
                          = submit_tag "Add this Comment"
            - comment.replies.each do |reply|
              %tr
                %td{:style =>"text-align:center;",:bgcolor=>'red'}
                  %h1="This is a reply: #{reply.body}"
            %tr
              %td{:colspan => "3"}
                %hr{:noshade => ""}

        - unless current_user.is_observer?
          %h1 Leave a comment
          = form_tag(comment_create_class_room_note_path(@class.id, @note), :multipart => true)   do |f|
            .field
              = text_area_tag "comment[comment]", nil, :rows => 4, :cols => 40
              = hidden_field_tag 'comment[user_id]',current_user.id
              = hidden_field_tag 'comment[class_room_id]',@class.id
            .actions
              = submit_tag "Add this Comment"
              %span#assignment_comment_ajax_loader{:style => "display: none"}= image_tag "LoaderIcon.gif"

app/views/notes/edit.html.haml
.headings
  %h1 Editing Class Notes
%br
= render 'form'

%br
= link_to 'Go Back', class_room_notes_path(@class.id)

app/views/notes/index.html.haml
%br
%br
  .headings
    %h1 Class Notes
    %br
    -if current_user.is_teacher? and !current_user.class_rooms.blank?
      =link_to 'Add new Class Notes', new_class_room_note_path(@class.id)
#user_content
  .tables  
    %table.assignments
      %tr.white
        %th Title
        %th Notes
        %th Posted
    
        - @notes.each do |note|
          %tr.desc
            - unless current_user.is_observer?
            %td! = link_to note.title, comment_new_class_room_note_path(@class.id, note)
            - else
              - if @student
              %td! = link_to note.title, go_to_student_note_class_room_note_path(@class.id, note, @student.id)
              - elsif @teacher
                %td! = link_to note.title, go_to_teacher_note_class_room_note_path(@class.id, note, @teacher.id)
            %td! = truncate(note.description, :length =>100, :separator => ' ')
            %td
              %center
                #{distance_of_time_in_words(note.created_at, Time.now)} ago
            -if current_user.is_teacher? and !current_user.class_rooms.blank?
              %td
              %td= link_to 'Edit', edit_class_room_note_path(@class.id, note)
              %td= link_to 'Delete', class_room_note_path(@class.id, note), :confirm => 'Are you sure?', :method => :delete

    %br
    -if current_user.is_teacher? and !current_user.class_rooms.blank?
      =link_to 'Add new Class Notes', new_class_room_note_path(@class.id)
  

app/views/notes/new.html.haml
.headings
  %h1 New Class Notes
  %br
  %hr
= render 'form'
%br
= link_to 'Back', class_room_notes_path(@class.id)

.textile_explanation
  %h1 Basic Textile Formatting Guide
  %br
  %ul
    %li _italics_
    %li *bold*
    %li ??citation??
    %li -deleted text-
    %li +inserted text+
    %li ^superscript^
    %li ~subscript~
    %li "linktext":http://…
  %br
  %h3
    For a more complete guide to everything you can do with Textile, visit #{link_to 'http://textile.thresholdstate.com/'}. ClassCloud supports all Textile features. It's an easy way to make your
    writing look great!

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @note.title
%p
  %b Description:
  = @note.description

= link_to 'Edit', edit_class_room_note_path(@class.id, @note)
\|
= link_to 'Back', class_room_notes_path(@class.id)