config/routes.rb
    match "user_profiles/:student_id"=> "user_profiles#index", :as => :user_profile, :via => :get
    devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
      match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
    end

    resources :upload_files do

      member do
        get "comment_new"
        post "comment_create"
        
        get "student/:student_id", :action => "show", :as => :show_student_upload_file
        get "teacher/:teacher_id", :action => "show", :as => :show_teacher_upload_file
        get "comment_student/:student_id", :action => "comment_new", :as => :go_to_student_upload_file
        get "comment_teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_upload_file
      end
      
      collection do
        get "download"
        get "student/:student_id", :action => "index", :as => :student_upload_files_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_upload_files_index
      end
      
    end

    resources :notes do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_note
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_note
        get "download"
        put "remove_file"
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_notes_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_notes_index
      end
    end
    
    resources :to_dos do
      collection do
        get "selected_time"
      end
    end

    resources :messages do
      member do
        get "student/:student_id", :action => "inbox_detail", :as => :student_inbox_detail_observer
        get "teacher/:teacher_id", :action => "inbox_detail", :as => :teacher_inbox_detail_observer

        get "download"
        get "edit_draft"
        post 'delete_draft'
        delete 'student/:student_id', :action => :destroy, :as => :student_observer_message_destroy
        delete 'teacher/:teacher_id', :action => :destroy, :as => :teacher_observer_message_destroy
      end
      collection do
        get "draft"
        get "sent"
        post "destroy_all_data"
        get "student/:student_id/sent", :action => :sent, :as => :student_observer_message_sent
        get "teacher/:teacher_id/sent", :action => :sent, :as => :teacher_observer_message_sent
        get "student/:student_id", :action => :index, :as => :student_observer_message_inbox
        get "teacher/:teacher_id", :action => :index, :as => :teacher_observer_message_inbox
        get "student/:student_id/new", :action => :new, :as => :student_observer_message_new
        get "teacher/:teacher_id/new", :action => :new, :as => :teacher_observer_message_new
        post "student/:student_id", :action => :create, :as => :student_observer_message_create
        post "teacher/:teacher_id", :action => :create, :as => :teacher_observer_message_create
      end
    end

    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    match "messages/inbox_detail/:id"=> "messages#inbox_detail", :as => :inbox_detail, :via => :get
    
    match "messages/sent_detail/:id"=> "messages#sent_detail", :as => :sent_detail, :via => :get
    match "messages/sent_detail/:id/student/:student_id"=> "messages#sent_detail", :as => :student_observer_sent_detail, :via => :get
    match "messages/sent_detail/:id/teacher/:teacher_id"=> "messages#sent_detail", :as => :teacher_observer_sent_detail, :via => :get
    
    match "messages/draft_detail/:id"=> "messages#draft_detail", :as => :draft_detail, :via => :get

    resources :assignments do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_assignment
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_assignment
        get "download"
        put "remove_file"
        get "edit_assignment_category", :action => "edit_assignment_category", :as => :edit_assignment_category
        put "update_assignment_category", :action => "update_assignment_category", :as => :update_assignment_category
        delete "delete_assignment_category", :action => "delete_assignment_category", :as => :delete_assignment_category
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_assignments_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_assignments_index
        get "assignment_category", :action => "assignment_category", :as => :assignment_category
        post "create_assignment_category", :action => "create_assignment_category", :as => :create_assignment_category
        get "new_assignment_category", :action => "new_assignment_category", :as => :new_assignment_category

      end

      resources :writeboards
    end

    resources :writeboards do
      
      member do
        post "comment_create"
        get "comment_edit/:comment_id", :action => "comment_edit", :as => :edit_writeboard_assignment
        delete "comment_destroy/:comment_id", :action => "comment_destroy", :as => :destroy_writeboard_comment
        put "comment_update/:comment_id", :action => "comment_update", :as => :update_writeboard_comment
        get "vote_up"
      end
      
      collection do
        get "student/:student_id", :action => "index", :as => :student_writeboards_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_writeboards_index
      end
    end

    match "/assignments/:id/comment_edit/:comment_id" => "assignments#comment_edit", :as => :comment_edit_assignment, :via => :get
    match "/assignments/:id/comment_update/:comment_id" => "assignments#comment_update", :as => :comment_update_assignment, :via => :put
    match "/assignments/:id/comment_destroy/:comment_id" => "assignments#comment_destroy", :as => :comment_destroy_assignment, :via => :delete

    match "/events/:id/comment_edit/:comment_id" => "calendar#comment_edit", :as => :comment_edit_event, :via => :get
    match "/events/:id/comment_update/:comment_id" => "calendar#comment_update", :as => :comment_update_event, :via => :put
    match "/events/:id/comment_destroy/:comment_id" => "calendar#comment_destroy", :as => :comment_destroy_event, :via => :delete

    match "/upload_files/:id/comment_edit/:comment_id" => "upload_files#comment_edit", :as => :comment_edit_upload_files, :via => :get
    match "/upload_files/:id/comment_update/:comment_id" => "upload_files#comment_update", :as => :comment_update_upload_files, :via => :put
    match "/upload_files/:id/comment_destroy/:comment_id" => "upload_files#comment_destroy", :as => :comment_destroy_upload_files, :via => :delete

    resources :calendar, :except => [:index, :create, :update]

    resources :events, :controller => :calendar do
      member do
        post "comment_create"
        get "download"
        put "remove_file"
      end
    end

    resources :people do
      collection do
        post "add_person_from_existing_people"
      end

      member do
        delete "remove_from_class"
      end
    end

    match "/notes/:id/comment_edit/:comment_id" => "notes#comment_edit", :as => :comment_edit_notes, :via => :get
    match "/notes/:id/comment_update/:comment_id" => "notes#comment_update", :as => :comment_update_notes, :via => :put
    match "/notes/:id/comment_destroy/:comment_id" => "notes#comment_destroy", :as => :comment_destroy_notes, :via => :delete

   
    resources :discussions do
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_discussion
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_discussion
        get "download"
        put "remove_file"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_discussion_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_discussion_index
      end
    end

    match "/discussions/:id/comment_edit/:comment_id" => "discussions#comment_edit", :as => :comment_edit_discussions, :via => :get
    match "/discussions/:id/comment_update/:comment_id" => "discussions#comment_update", :as => :comment_update_discussions, :via => :put
    match "/discussions/:id/comment_destroy/:comment_id" => "discussions#comment_destroy", :as => :comment_destroy_discussions, :via => :delete

    match "/student/:student_id" => "class_rooms#show", :as => :student, :via => :get
    match "/teacher/:teacher_id" => "class_rooms#show", :as => :teacher, :via => :get
  end

  resources :events, :only => :show, :controller => :calendar do
    member do
      get "student/:student_id", :action => "show"
      get "teacher/:teacher_id", :action => "show"
    end
  end

  match "/before_activation" => "people#pick_username_and_password", :as => :pick_username_and_password, :via => :get
  match "/activation" => "people#save_username_and_password", :as => :save_username_and_password, :via => :post
  match "/student/:id/dashboard" => "dashboard#index", :as => :student_dashboard, :via => :get
  match "/teacher/:teacher_id/dashboard" => "dashboard#index", :as => :teacher_dashboard, :via => :get
  match "/teacher/:teacher_id/dashboard/student/:student_id/activity_feed" => "dashboard#index", :as => :student_activity_feed, :via => :get
  match 'pages/guest', to: 'pages#guest', as: :guest
  match 'pages/getting_started', to: 'pages#getting_started', as: :getting_started
  match 'pages/development', to: 'pages#development', as: :development
  match 'users/password/new', to: 'users#password#new', as: :account_help
  devise_for :users

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  acts_as_commentable

  belongs_to :user
  belongs_to :class_room
  
  validates :title, :description, :user_id, :class_room_id, :presence => true
  validates :title, :uniqueness => {:scope => [:user_id, :class_room_id]}
  
  acts_as_textiled :description
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  log_activity_streams :current_user, :full_name, :commented,
    :@discussion, :title, :comment_create, :discussion

  log_activity_streams :current_user, :full_name, :started,
    :@discussion, :title, :create, :discussion

  before_filter :authenticate_user!
  before_filter :get_my_students_and_class

  def index
    @discussions = @class.discussions
  end

  def show
    @discussion = Discussion.find(params[:id])
  end

  def new
    @discussion = Discussion.new
  end

  def edit
    @discussion = Discussion.find(params[:id])
  end

  def create
    @discussion = Discussion.new(params[:discussion])
    @discussion.class_room_id = params[:class_room_id]

    if @discussion.save
      redirect_to (class_room_discussions_url(@class.id)), notice: 'Discussion was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @discussion = Discussion.find(params[:id])

    if @discussion.update_attributes(params[:discussion])
      redirect_to (class_room_discussions_url(@class.id)), notice: 'Discussion was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy
    
    redirect_to (class_room_discussions_url(@class.id))
  end
  
  def comment_new
    @discussion = Discussion.find(params[:id])
  end

  def comment_create
    @discussion = Discussion.find(params[:id])
    @discussion.comments.create(params[:comment])
    
    redirect_to :back
  end


  def comment_destroy
    @discussion = Discussion.find(params[:id])
    comment = @discussion.comments.find(params[:comment_id])
    comment.destroy if comment
    
    render :action => "comment_new"
  end

  def comment_edit
    @discussion = Discussion.find(params[:id])
    @comment = @discussion.comments.find(params[:comment_id])
  end

  def comment_update
    @discussion = Discussion.find(params[:id])
    @comment = @discussion.comments.find(params[:comment_id])

    if params[:comment][:file].nil?
      params[:comment][:file] = @comment.file.path
    else
      params[:comment][:file]
    end
    if @comment.update_attributes(params[:comment])
      redirect_to class_room_discussions_url(@class.id)
    else
      render :action => "comment_edit"
    end
  end

  def download
    file = Comment.find(params[:id])
    send_file file.file.path, :type => file.file_content_type

  end

  def remove_file
    file = Comment.find(params[:id])
    if file.update_attributes(:file_updated_at =>'')
      redirect_to class_room_discussions_url(@class.id)
    else
      render :action => "comment_edit"
    end
  end

  private

  def get_my_students_and_class
    @class = if current_user.is_teacher?
      current_user.class_rooms.find(params[:class_room_id])
    elsif current_user.is_student?
      my_class_room = current_user.class_room_students.where(class_room_id: params[:class_room_id]).first
      my_class_room.class_room
    elsif current_user.is_observer?
      if params[:student_id]
        @student = User.find params[:student_id]
        student_class_room = @student.class_room_students.where(class_room_id: params[:class_room_id]).first
        student_class_room.class_room if student_class_room
      elsif params[:teacher_id]
        @teacher = User.find params[:teacher_id]
        ClassRoom.find params[:class_room_id]
      end
    end
    @students = @class.students
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.haml
- if @discussion.new_record?
  = form_for @discussion, :url => class_room_discussions_path(@class.id) do |f|
    -if @discussion.errors.any?
      #error_explanation
        %h2= "#{pluralize(@discussion.errors.count, "error")} prohibited this discussion from being saved:"
        %ul
          - @discussion.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_field :title, :placeholder => "Enter a title"
    .field
      = f.text_area :description, :rows => 36, :cols => 100, :placeholder => "Remember, you can use Textile to format the text. See the bottom of the page for instructions!"
      = f.hidden_field :user_id,:value=>current_user.id
    .actions
      = f.submit 'Save'
- else
  = form_for @discussion, :url => class_room_discussion_path(@class.id, @discussion.id) do |f|
    -if @discussion.errors.any?
      #error_explanation
        %h2= "#{pluralize(@discussion.errors.count, "error")} prohibited this discussion from being saved:"
        %ul
          - @discussion.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_field :title, :placeholder => "Enter a title"
    .field
      = f.text_area :description, :rows => 36, :cols => 100, :placeholder => "Remember, you can use Textile to format the text. See the bottom of the page for instructions!"
      = f.hidden_field :user_id,:value=>current_user.id
    .actions
      = f.submit 'Save'

app/views/discussions/comment_edit.html.haml
%table{:width => "50%"}
  %tr
    %td
      %b= @discussion.title
    %td{:align => "right"}
      = link_to "New", new_class_room_discussion_path(@class.id)
      - if current_user.id.eql?(@discussion.user_id) or current_user.is_teacher?
        = "|"
        = link_to "Edit", edit_class_room_discussion_path(@class.id, @discussion)
        = "|"
        = link_to "Delete", class_room_discussion_path(@class.id, @discussion), :confirm => "Are you sure ?", :method => :delete
  
  %tr
    %td{:colspan => "2"}
      From: #{user_full_name(@discussion.user)}
  %tr
    %td{:colspan => "2"}
      Date: #{date_format(@discussion.created_at)}

  %tr
    %td{:colspan => "2"}
      %hr{:noshade => ""}
  %tr
    %td{:colspan => "2"}
      = @discussion.description
  %tr
    %td{:colspan => "2"}
      %hr{:noshade => ""}
  %tr
    %td{:colspan => "3"}
      #comments_container
        - @discussion.comments.each do |comment|
          %table{:width => "100%"}
            %tr
              %td{:rowspan => "3"}= image_tag "bakso.jpg", :width => "48", :height => "48"
              %td{:colspan => "3"}
                = "#{user_full_name(comment.user)}"
                - unless vote_count(comment.id).eql?(0) or !current_user.is_teacher?
                  = '('
                  = vote_count(comment.id)
                  = ')'
                %br
                = "#{date_format(comment.created_at)}"
            %tr
              %td
                = comment.comment
                - unless comment.file_updated_at.nil?
                  %br
                  = 'file :'
                  - if current_user.is_observer?
                    = comment.file_file_name
                  - else
                    - if current_user.id.eql?(comment.user_id) or current_user.is_teacher?
                      = link_to comment.file_file_name, download_class_room_note_path(@class.id, comment.id)

                      | #{link_to 'remove',remove_file_class_room_discussion_path(@class.id, comment.id), :confirm => "Are you sure ?", :method => :put}
              %td{:align => "right"}
                - if current_user.id.eql?(comment.user_id) or current_user.is_teacher?
                  = link_to "Edit", class_room_comment_edit_discussions_path(@class.id, @discussion, comment.id)
                  | #{link_to "Delete", class_room_comment_destroy_discussions_path(@class.id, @discussion, comment.id), :method => :delete}
                - unless vote_comment(comment).nil?
                  = 'Wee!!'
                - else
                  = link_to 'Weee!!',class_room_comment_vote_path(@class.id ,@discussion.id,comment,:commentable_type =>"#{params[:controller]}")
                - if current_user.id.eql?(@discussion.user_id) and !current_user.id.eql?(comment.user_id) and comment.replies.count.eql?(0)
                  = link_to 'Reply', '#',:onclick => "$('.reply_#{comment.id}').show()"
                  %div{:class =>"reply_#{comment.id}", :style=> "display: none;"}
                    %h1=link_to 'x','#',:onclick => "$('.reply_#{comment.id}').hide()"
                    = form_tag(class_room_reply_comment_path(@class.id, comment.id), :multipart => true)   do |f|
                      .field
                        = text_area_tag "reply[body]", nil, :rows => 4, :cols => 40
                        = hidden_field_tag 'reply[user_id]',comment.user_id
                        = hidden_field_tag 'reply[replier_id]',current_user.id
                        = hidden_field_tag 'reply[comment_id]',comment.id
                        = hidden_field_tag 'comment_controller',"#{params[:controller]}"
                        = hidden_field_tag 'id',"#{params[:id]}"
                      .actions
                        = submit_tag "Add this Comment"
            - comment.replies.each do |reply|
              %tr
                %td{:style =>"text-align:center;",:bgcolor=>'red'}
                  %h1="This is a reply: #{reply.body}"
            %tr
              %td{:colspan => "3"}
                %hr{:noshade => ""}
%h1 Update a comment
= form_tag(class_room_comment_update_discussions_path(@class.id, @discussion, @comment.id), :method => :put,:multipart =>true) do |f|
  .field
    = text_area_tag "comment[comment]", @comment.comment, :rows => 4, :cols => 40
    %br
    = file_field_tag "comment[file]"
  .actions
    = submit_tag "Update this Comment"

app/views/discussions/comment_new.html.haml
.standard_text
  %h3 Started #{distance_of_time_in_words(@discussion.created_at, Time.now)} ago by #{user_full_name(@discussion.user)}.
  %hr
  - if current_user.id.eql?(@discussion.user_id) or current_user.is_teacher?
    = link_to "Edit", edit_class_room_discussion_path(@class.id, @discussion)
    = "|"
    = link_to "Delete", class_room_discussion_path(@class.id, @discussion), :confirm => "Are you sure ?", :method => :delete
  %br
    %br
      %br
        #user_content
          .user_titles
            %h1
              = @discussion.title
          .textile
            != @discussion.description
            %br
          %tr
        %hr
        %hr
          %tr
            %td{:colspan => "3"}
        #comments_container
          %h4 Comments
          %br
          - @discussion.comments.each do |comment|
            %table{:width => "100%"}
              %tr
                %h6{:colspan => "3"}
                  = "#{user_full_name(comment.user)}"
                  - unless vote_count(comment.id).eql?(0) or current_user.is_teacher?
                    = "(#{vote_count(comment.id)})"
                  said this #{distance_of_time_in_words(comment.created_at, Time.now)} ago:
              %tr
              %br
              %h4
                = comment.comment
                %td{:align => "right"}
                  %div{:id=>"comment"+comment.id.to_s}
                    - if current_user.id.eql?(comment.user_id)
                      = link_to "Edit", class_room_comment_edit_discussions_path(@class.id, @discussion, comment.id)
                      | #{link_to "Delete", class_room_comment_destroy_discussions_path(@class.id, @discussion, comment.id), :method => :delete}
                    - elsif current_user.id.eql?(comment.user_id) or current_user.is_teacher?
                      = link_to "Delete", class_room_comment_destroy_discussions_path(@class.id, @discussion, comment.id), :method => :delete
                    - unless vote_comment(comment).nil?
                      = image_tag('supercool_button_grey.png')
                    - else
                      = link_to image_tag('supercool_button.png'),class_room_comment_vote_path(@class.id ,@discussion.id,comment,:commentable_type =>"#{params[:controller]}")
                    - if current_user.id.eql?(@discussion.user_id) and !current_user.id.eql?(comment.user_id) and comment.replies.count.eql?(0)
                      /= link_to 'Reply', '#',:onclick => "$('.reply_#{comment.id}').show()"
                      %div{:class =>"reply_#{comment.id}", :style=> "display: none;"}
                        %h1=link_to 'x','#',:onclick => "$('.reply_#{comment.id}').hide()"
                        = form_tag(class_room_reply_comment_path(@class.id, comment.id), :multipart => true)   do |f|
                          .field
                            = text_area_tag "reply[body]", nil, :rows => 4, :cols => 40
                            = hidden_field_tag 'reply[user_id]',comment.user_id
                            = hidden_field_tag 'reply[replier_id]',current_user.id
                            = hidden_field_tag 'reply[comment_id]',comment.id
                            = hidden_field_tag 'comment_controller',"#{params[:controller]}"
                            = hidden_field_tag 'id',"#{params[:id]}"
                          .actions
                            = submit_tag "Add this Comment"
              - comment.replies.each do |reply|
                %tr
                  %td{:style =>"text-align:center;",:bgcolor=>'red'}
                    %h1="This is a reply: #{reply.body}"
              %tr
                %td{:colspan => "3"}
                  %hr{:noshade => ""}
  - unless current_user.is_observer?
    %h1 Leave a comment
    = form_tag(comment_create_class_room_discussion_path(@class.id, @discussion),:multipart =>true) do |f|
      .field
        = text_area_tag "comment[comment]", nil, :rows => 4, :cols => 40
        %br
        = hidden_field_tag 'comment[user_id]',current_user.id
        = hidden_field_tag 'comment[class_room_id]',@class.id
      .actions
        = submit_tag "Add this Comment"
        %span#assignment_comment_ajax_loader{:style => "display: none"}= image_tag "LoaderIcon.gif"

app/views/discussions/edit.html.haml
.headings
  %h1 Edit discussion

= render 'form'
%br
= link_to 'Go Back', class_room_discussions_path(@class.id)

app/views/discussions/index.html.haml
%br
%br
  .headings
    %h1 Discussions
    %br
    - unless current_user.is_observer?
      = link_to "Start a New Discussion", new_class_room_discussion_path(@class.id)
#user_content  
  .tables
    %table.assignments
      %tr.white
        %th Topic
        %th Content
  
      - @discussions.each do |discussion|
        %tr.desc
          - unless current_user.is_observer?
            %td!= link_to discussion.title, comment_new_class_room_discussion_path(@class.id, discussion)
          - else
            - if @student
              %td! = link_to discussion.title, go_to_student_discussion_class_room_discussion_path(@class.id, discussion, @student.id)
            - elsif @teacher
              %td! = link_to discussion.title, go_to_teacher_discussion_class_room_discussion_path(@class.id, discussion, @teacher.id)
          %td! = truncate(discussion.description, :length =>100, :separator => ' ')
          - if current_user.id.eql?(discussion.user_id) 
            %td= link_to 'Edit', edit_class_room_discussion_path(@class.id, discussion)
          - if current_user.id.eql?(discussion.user_id) or current_user.is_teacher?
            %td= link_to 'Delete', class_room_discussion_path(@class.id, discussion), :confirm => 'Are you sure?', :method => :delete
    

app/views/discussions/new.html.haml
.headings
  %h1 New discussion
  %br
  %hr

= render 'form'
%br

= link_to 'Back', class_room_discussions_path(@class.id)

.textile_explanation
  %h2 Basic Textile Formatting Guide
  %hr
  %ul
    %li _italics_
    %li *bold*
    %li ??citation??
    %li -deleted text-
    %li +inserted text+
    %li ^superscript^
    %li ~subscript~
    %li "linktext":http://…
  %br
  %h3
    For a more complete guide to everything you can do with Textile, visit #{link_to 'http://textile.thresholdstate.com/'}. ClassCloud supports all Textile features. It's an easy way to make your
    writing look great!

app/views/discussions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @discussion.title
%p
  %b Description:
  = @discussion.description
%p
  %b User:
  = @discussion.user_id

= link_to 'Edit', edit_class_room_discussion_path(@class.id, @discussion)
\|
= link_to 'Back', class_room_discussions_path(@class.id)