config/routes.rb
Tes::Application.routes.draw do
  resources :user_meeting_rooms

  resources :meeting_rooms do
    get "user",:on =>:collection
    get "moderator", :on =>:member
    put "add_moderator", :on =>:member
    member do
      get "comment_new"
      post "comment_create"
    end
  end
  match "meeting_rooms/:id/comment_edit/:comment_id"=> "meeting_rooms#comment_edit", :as => :edit_meeting_room_comment, :via => :get
  match "meeting_rooms/:id/comment_update/:comment_id"=> "meeting_rooms#comment_update", :as => :update_meeting_room_comment, :via => :put
  match "meeting_rooms/:id/comment_destroy/:comment_id"=> "meeting_rooms#comment_destroy", :as => :destroy_meeting_room_comment, :via => :delete

  resources :states do
    get :autocomplete_state_name, :on => :collection
  end
  get "admins/index"

  get "pages/index"

  match "pages/city/:city"=> "pages#city", :as => :state_city, :via => :get
  match "pages/school/:school"=> "pages#school", :as => :school_city, :via => :get
  match "pages/search_state/"=> "pages#search_state", :as => :search_state, :via => :get
  match "pages/country/"=> "pages#country", :as => :country, :via => :get
  match "pages/city_list/:country_id"=> "pages#city_list", :as => :city_list, :via => :get
  match "pages/states_list/"=> "pages#state_list", :as => :state_list, :via => :get

  namespace :admin do

    resources :admins do
      member do
        put "update"
        get "edit_school"
        put "update_school"
      end
      collection do
        get "school"
        get "new_school"
        post "create_school"
      end

    end

  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" } do
    get "welcome"=> "devise/registrations#index", :as => :welcome
  end

  devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
    match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
  end

  resources :activity_stream_preferences
  resources :activity_streams
  resources :class_rooms do

    match "reply/:comment_id"=> "comments#reply", :as => :reply_comment, :via => :post

    match "voteable_type/:id/comment_vote/:comment_id"=> "comments#index", :as => :comment_vote, :via => :get
    match "user_profiles/:student_id"=> "user_profiles#index", :as => :user_profile, :via => :get
    devise_for :users, :controllers => {:registrations => "devise/registrations" }, :only =>:edit do
      match "user/:id"=> "devise/registrations#edit", :as => :edit_user, :via => :get
    end

    resources :upload_files do

      member do
        get "comment_new"
        post "comment_create"
        
        get "student/:student_id", :action => "show", :as => :show_student_upload_file
        get "teacher/:teacher_id", :action => "show", :as => :show_teacher_upload_file
        get "comment_student/:student_id", :action => "comment_new", :as => :go_to_student_upload_file
        get "comment_teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_upload_file
      end
      
      collection do
        get "download"
        get "student/:student_id", :action => "index", :as => :student_upload_files_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_upload_files_index
      end
      
    end

    resources :notes do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_note
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_note
        get "download"
        put "remove_file"
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_notes_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_notes_index
      end
    end
    
    resources :to_dos do
      collection do
        get "selected_time"
      end
    end

    resources :messages do
      member do
        get "student/:student_id", :action => "inbox_detail", :as => :student_inbox_detail_observer
        get "teacher/:teacher_id", :action => "inbox_detail", :as => :teacher_inbox_detail_observer

        get "download"
        get "edit_draft"
        post 'delete_draft'
        delete 'student/:student_id', :action => :destroy, :as => :student_observer_message_destroy
        delete 'teacher/:teacher_id', :action => :destroy, :as => :teacher_observer_message_destroy
      end
      collection do
        get "draft"
        get "sent"
        post "destroy_all_data"
        get "student/:student_id/sent", :action => :sent, :as => :student_observer_message_sent
        get "teacher/:teacher_id/sent", :action => :sent, :as => :teacher_observer_message_sent
        get "student/:student_id", :action => :index, :as => :student_observer_message_inbox
        get "teacher/:teacher_id", :action => :index, :as => :teacher_observer_message_inbox
        get "student/:student_id/new", :action => :new, :as => :student_observer_message_new
        get "teacher/:teacher_id/new", :action => :new, :as => :teacher_observer_message_new
        post "student/:student_id", :action => :create, :as => :student_observer_message_create
        post "teacher/:teacher_id", :action => :create, :as => :teacher_observer_message_create
      end
    end

    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    match "messages/inbox_detail/:id"=> "messages#inbox_detail", :as => :inbox_detail, :via => :get
    
    match "messages/sent_detail/:id"=> "messages#sent_detail", :as => :sent_detail, :via => :get
    match "messages/sent_detail/:id/student/:student_id"=> "messages#sent_detail", :as => :student_observer_sent_detail, :via => :get
    match "messages/sent_detail/:id/teacher/:teacher_id"=> "messages#sent_detail", :as => :teacher_observer_sent_detail, :via => :get
    
    match "messages/draft_detail/:id"=> "messages#draft_detail", :as => :draft_detail, :via => :get

    resources :assignments do
      
      member do
        get "comment_new"
        post "comment_create"
        get "student/:student_id", :action => "comment_new", :as => :go_to_student_assignment
        get "teacher/:teacher_id", :action => "comment_new", :as => :go_to_teacher_assignment
        get "download"
        put "remove_file"
        get "edit_assignment_category", :action => "edit_assignment_category", :as => :edit_assignment_category
        put "update_assignment_category", :action => "update_assignment_category", :as => :update_assignment_category
        delete "delete_assignment_category", :action => "delete_assignment_category", :as => :delete_assignment_category
        get "vote_up"
      end

      collection do
        get "student/:student_id", :action => "index", :as => :student_assignments_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_assignments_index
        get "assignment_category", :action => "assignment_category", :as => :assignment_category
        post "create_assignment_category", :action => "create_assignment_category", :as => :create_assignment_category
        get "new_assignment_category", :action => "new_assignment_category", :as => :new_assignment_category

      end

      resources :writeboards
    end

    resources :writeboards do
      
      member do
        post "comment_create"
        get "comment_edit/:comment_id", :action => "comment_edit", :as => :edit_writeboard_assignment
        delete "comment_destroy/:comment_id", :action => "comment_destroy", :as => :destroy_writeboard_comment
        put "comment_update/:comment_id", :action => "comment_update", :as => :update_writeboard_comment
        get "vote_up"
      end
      
      collection do
        get "student/:student_id", :action => "index", :as => :student_writeboards_index
        get "teacher/:teacher_id", :action => "index", :as => :teacher_writeboards_index
      end
    end

    match "/assignments/:id/comment_edit/:comment_id" => "assignments#comment_edit", :as => :comment_edit_assignment, :via => :get
    match "/assignments/:id/comment_update/:comment_id" => "assignments#comment_update", :as => :comment_update_assignment, :via => :put
    match "/assignments/:id/comment_destroy/:comment_id" => "assignments#comment_destroy", :as => :comment_destroy_assignment, :via => :delete

    match "/events/:id/comment_edit/:comment_id" => "calendar#comment_edit", :as => :comment_edit_event, :via => :get
    match "/events/:id/comment_update/:comment_id" => "calendar#comment_update", :as => :comment_update_event, :via => :put
    match "/events/:id/comment_destroy/:comment_id" => "calendar#comment_destroy", :as => :comment_destroy_event, :via => :delete

    match "/upload_files/:id/comment_edit/:comment_id" => "upload_files#comment_edit", :as => :comment_edit_upload_files, :via => :get
    match "/upload_files/:id/comment_update/:comment_id" => "upload_files#comment_update", :as => :comment_update_upload_files, :via => :put
    match "/upload_files/:id/comment_destroy/:comment_id" => "upload_files#comment_destroy", :as => :comment_destroy_upload_files, :via => :delete

    resources :calendar, :except => [:index, :create, :update]

    resources :events, :controller => :calendar do
      member do
        post "comment_create"
        get "download"
        put "remove_file"
      end
    end

    resources :people do
      collection do
        post "add_person_from_existing_people"
      end

      member do
        delete "remove_from_class"
      end
    end

    match "/notes/:id/comment_edit/:comment_id" => "notes#comment_edit", :as => :comment_edit_notes, :via => :get
    match "/notes/:id/comment_update/:comment_id" => "notes#comment_update", :as => :comment_update_notes, :via => :put
    match "/notes/:id/comment_destroy/:comment_id" => "notes#comment_destroy", :as => :comment_destroy_notes, :via => :delete

   

app/views/admin/admins/edit.html.haml
%h1 edit user
= form_tag admin_admin_path(@user.id),:method =>:put do
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this discussion from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  = label_tag 'first_name'
  = text_field_tag 'user[first_name]',@user.first_name
  %br
  = label_tag 'last_name'
  = text_field_tag 'user[last_name]',@user.last_name
  %br
  = label_tag 'username'
  = text_field_tag 'user[username]',@user.username
  %br
  = label_tag 'time zone'
  = time_zone_select 'user','time_zone',nil, :default=>@user.time_zone
  %br
  = submit_tag 'Save'   

app/views/admin/admins/edit_school.html.haml
%h3 Edit School
%br
- if @state.nil?
  - country = @country
- else
  - country = @state
=form_tag update_school_admin_admin_path(country.id,:old_city=>@city,:school=>@school.id,:country_id=>@country.id),:method=>:put do
  %div#edit_school
    - if @country.name.eql?('USA')
      %h3 Country : #{@country.name}
      = hidden_field_tag 'country[name2]',@country.name
    - else
      %h3 Country
      = text_field_tag 'country[name]',@country.name,:placeholder=>"enter country name"
    %br
    %h3 State
    - if @country.name.eql?('USA')
      = select_tag "state[name]", options_from_collection_for_select(@states,'id','name',@state.id), :include_blank => true
    - else
      = text_field_tag 'state[name2]',@state.name,:placeholder=>"enter state name"
    %br
    %h3 City
    = text_field_tag 'city[name]',@city.name,:placeholder=>"enter city name"
    %br
    %h3 School
    = text_field_tag 'new_school[name]',@school.name,:placeholder=>"enter school name"
    %br
    = submit_tag 'Save',:onclick=>'checkFieldEditSchool();'

app/views/admin/admins/index.html.haml
%h1 Welcome #{current_user.full_name}!! 
= link_to 'Add User',new_admin_admin_path
%table{:border =>'1',:align =>'left'}
  %caption
    %b Teacher
  %tr
    %td
      %b Full name
    %td
      %b Edit?
    %td
      %b Delete?
    - @teachers.each do |teacher|
      %tr
        %td= teacher.full_name
        %td= link_to 'edit?',edit_admin_admin_path(teacher.id)
        %br
        %td= link_to 'delete?',admin_admin_path(teacher.id),:confirm =>'Are you sure?',:method =>:delete

%table{:border =>'1',:align =>'left'}
  %caption
    %b Student
  %tr
    %td
      %b Full name
    %td
      %b Edit?
    %td
      %b Delete?
    - @students.each do |student|
      %tr
        %td= student.full_name
        %td= link_to 'edit?',edit_admin_admin_path(student.id)
        %td= link_to 'delete?',admin_admin_path(student.id),:confirm =>'Are you sure?',:method =>:delete
%table{:border =>'1',:align =>'left'}
  %caption
    %b Observer
  %tr
    %td
      %b Full name
    %td
      %b Edit?
    %td
      %b Delete?
    - @observers.each do |observer|
      %tr
        %td= observer.full_name
        %td= link_to 'edit?',edit_admin_admin_path(observer.id)
        %td= link_to 'delete?',admin_admin_path(observer.id),:confirm =>'Are you sure?',:method =>:delete

%br

app/views/admin/admins/new.html.haml
%h1 new user
= form_tag admin_admins_path(@user.id),:method =>:post do
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this discussion from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  = label_tag 'first_name'
  = text_field_tag 'user[first_name]'
  %br
  = label_tag 'last_name'
  = text_field_tag 'user[last_name]'
  %br
  = label_tag 'Email'
  = email_field_tag 'user[email]'
  %br
  = label_tag 'time zone'
  = time_zone_select 'user','time_zone',nil
  %br
  = label_tag 'User Type'
  = select("user", "user_type", { "Admin" => "admin", "Teacher" => "teacher", "Observer" => "observer"})
  %br
  = submit_tag 'Save'

app/views/admin/admins/new_school.html.haml
%div
=form_tag create_school_admin_admins_path do
  %h3 Country
  = text_field_tag 'country',nil,:placeholder=>"enter country name"
  %br
  %h3 State
  = text_field_tag 'state',nil,:placeholder=>"enter state name"
  %br
  %h3 City
  = text_field_tag 'city',nil,:placeholder=>"enter city name"
  %br
  %h3 School
  = text_field_tag 'school',nil,:placeholder=>"enter school name"
  %br
  =submit_tag 'save'

app/views/admin/admins/school.html.haml
%br
= 'All Schools'
%br
= link_to 'New School',new_school_admin_admins_path
%div#school_list
  %div#state{:style=>"float:left;"}
    = 'The school not in USA?'
    = link_to 'Click Here','#',:onclick => "$('#state').hide();$('#country').show();"
    %br
    = "State :"
    = select_tag "state[name]", options_from_collection_for_select(@states,'id','name',params[:client]), :include_blank => true,:onchange=> "showCity(this.value);$('#loader').show();"
    
  %div#country{:style=>"display:none;float:left"}
    = 'The school in USA?'
    = link_to 'Click Here','#',:onclick => "$('#state').show();$('#country').hide();"
    %br
    = "Country :"
    = select_tag "state[name]", options_from_collection_for_select(@countries,'id','name',params[:client]), :include_blank => true,:onchange=> "showCity(this.value,'country');$('#loader').show();"
    
  %div#city_name{:style=>"float:left;"}
  %div#school_name{:style=>"float:center;"}
  %div#loader{:style=>"display:none;float:left;"}
    = image_tag('ajax-loading.gif')
  